name: Laravel CI

on: [push]

jobs:
  laravel-test:
    runs-on: self-hosted

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3006:3006
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set UP PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        extensions: mbstring, bcmath, pdo, pdo_mysql

    - name: Install packages
      run: composer update

    - name: Set App
      run: cp .env.example .env

    - name: Set Key
      run: |
        php artisan config:clear
        php artisan key:generate

    - name: Run test
      id: test_1
      run: vendor/bin/phpunit
      
    - name: deploy
      if: steps.test_1.outcome == 'success'
      run: ls

    - name: Artifact
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: artifacts
        path: |
          composer.json
          storage/logs/laravel.log

    - name: Action on github-actions-server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KEY_SERVER }}" >> ~/.ssh/id_rsa
        chmod 600 ~/.ssh/di_rsa
        ssh-keyscan -H

    - name: LS via ssh
      run: ssh root@github-actions-host.matanga.com.ar -p 1022 "ls -ltrah"